
language: perl
perl:
    - "5.14"
    - "5.12"


before_install:
   - sudo apt-get update  -qq
   - sudo apt-get install -qq libjson-xs-perl devscripts git-core debhelper
   - git config --global user.email "test@test.com"
   - git config --global user.name "Mr Test"
