#!/bin/bash
#############################################################
# Get latest revision depending on the last tag
#############################################################


# TODO: add check for verison to have just 3 numbers, truncate the rest
# do the same in debianize.sh or make another script that just gnerates the version
NEW_VERSION=`git describe 2>/dev/null | awk -F'-g[0-9a-fA-F]+' '{print $1}' | sed -e 's/\-/./g' `
if [[ -z $NEW_VERSION ]]; then
  NEW_VERSION="0.0.1";
fi

read -r -p "Will create tag with version [$NEW_VERSION]. Are you sure ? [Y/n] " response
case $response in
    [yY][eE][sS]|[yY]) 
        git tag -a "$NEW_VERSION" -m "Creating tag for version $NEW_VERSION";
        exit 0;
        ;;
    *)
        exit -1
        ;;
esac

